######################################################################
# Automatically generated by qmake (1.07a) Sat Jun 4 13:50:28 2005
######################################################################

TEMPLATE = app

CONFIG += qt opengl warn_on release
CONFIG -= dlopen_opengl

DEPENDPATH	= ../include

REQUIRES        = opengl

HEADERS += bbb_Form.h bbb_GLWidget.h
SOURCES += bbb_Form.cpp bbb_GLWidget.cpp Brick-by-Brick.cpp